// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function addItem(cart, item) {
  return /* :: */[
          item,
          cart
        ];
}

function updateItem(cart, productId, quantity) {
  var item = List.find((function (i) {
          return i[/* productId */0] === productId;
        }), cart);
  return /* record */[
          /* productId */item[/* productId */0],
          /* title */item[/* title */1],
          /* unitPrice */item[/* unitPrice */2],
          /* currency */item[/* currency */3],
          /* quantity */quantity
        ];
}

var cart_000 = /* record */[
  /* productId */"B5",
  /* title */"Web Principles",
  /* unitPrice */18.00,
  /* currency */"USD",
  /* quantity */8
];

var cart_001 = /* :: */[
  /* record */[
    /* productId */"B4",
    /* title */"Web UX",
    /* unitPrice */12.00,
    /* currency */"USD",
    /* quantity */3
  ],
  /* [] */0
];

var cart = /* :: */[
  cart_000,
  cart_001
];

var updatedItem = updateItem(cart, "B4", 6);

console.log(updatedItem[/* title */1] + (". Updated Quantity: " + String(updatedItem[/* quantity */4])));

exports.addItem = addItem;
exports.updateItem = updateItem;
exports.cart = cart;
exports.updatedItem = updatedItem;
/* updatedItem Not a pure module */
