// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function addItem(cart, item) {
  return /* :: */[
          item,
          cart
        ];
}

function getTotalPrice(cart) {
  var folder = function (acc, item) {
    return acc + item[/* unitPrice */2] * item[/* quantity */4];
  };
  return List.fold_left(folder, 0, cart);
}

var cart_000 = /* record */[
  /* productId */"B5",
  /* title */"Measure What Matters",
  /* unitPrice */14.99,
  /* currency */"USD",
  /* quantity */8
];

var cart_001 = /* :: */[
  /* record */[
    /* productId */"B4",
    /* title */"The Silk Roads: A New History of the World",
    /* unitPrice */13.59,
    /* currency */"USD",
    /* quantity */3
  ],
  /* [] */0
];

var cart = /* :: */[
  cart_000,
  cart_001
];

console.log(getTotalPrice(cart));

exports.addItem = addItem;
exports.getTotalPrice = getTotalPrice;
exports.cart = cart;
/*  Not a pure module */
