// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Seed$S2funway = require("./Seed.bs.js");

function printCart(items) {
  return List.iter((function (i) {
                console.log(i[/* productId */0] + (" " + (i[/* title */1] + (". Quantity: " + String(i[/* quantity */4])))));
                return /* () */0;
              }), items);
}

function updateItem(items, productId, quantity) {
  var mitems = List.map((function (i) {
          var item = i;
          if (item[/* productId */0] === productId) {
            return /* record */[
                    /* productId */item[/* productId */0],
                    /* title */item[/* title */1],
                    /* unitPrice */item[/* unitPrice */2],
                    /* currency */item[/* currency */3],
                    /* quantity */quantity
                  ];
          } else {
            return item;
          }
        }), items);
  if (mitems) {
    return /* Ok */Block.__(0, [mitems]);
  } else {
    return /* Error */Block.__(1, ["Empty cart"]);
  }
}

var match = updateItem(Seed$S2funway.Seed[/* cartItems */0], "Book-1", 11);

if (match.tag) {
  console.log(match[0]);
} else {
  printCart(match[0]);
}

console.log("*********************");

var match$1 = updateItem(/* [] */0, "Book-1", 11);

if (match$1.tag) {
  console.log(match$1[0]);
} else {
  printCart(match$1[0]);
}

exports.printCart = printCart;
exports.updateItem = updateItem;
/* match Not a pure module */
