// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Seed$S2funway = require("./Seed.bs.js");

function printCart(_items) {
  while(true) {
    var items = _items;
    if (items) {
      var h = items[0];
      console.log(h[/* productId */0] + (h[/* title */1] + (". Quantity: " + String(h[/* quantity */4]))));
      _items = items[1];
      continue ;
    } else {
      console.log("...");
      return /* () */0;
    }
  };
}

function updateItem(items, productId, quantity) {
  var updateItem_Internal = function (items, productId, quantity) {
    var _items = items;
    while(true) {
      var items$1 = _items;
      if (items$1) {
        var h = items$1[0];
        var tail = items$1[1];
        if (h[/* productId */0] === productId) {
          return /* :: */[
                  /* record */[
                    /* productId */h[/* productId */0],
                    /* title */h[/* title */1],
                    /* unitPrice */h[/* unitPrice */2],
                    /* currency */h[/* currency */3],
                    /* quantity */quantity
                  ],
                  tail
                ];
        } else {
          _items = tail;
          continue ;
        }
      } else {
        return items$1;
      }
    };
  };
  if (items) {
    return /* Ok */Block.__(0, [updateItem_Internal(items, productId, quantity)]);
  } else {
    return /* Error */Block.__(1, ["Empty cart"]);
  }
}

var match = updateItem(Seed$S2funway.Seed[/* cartItems */0], "Book-1", 6);

if (match.tag) {
  console.log(match[0]);
} else {
  printCart(match[0]);
}

exports.printCart = printCart;
exports.updateItem = updateItem;
/* match Not a pure module */
