// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Seed$S2funway = require("./Seed.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function getItemById(itemId) {
  var exit = 0;
  var item;
  try {
    item = List.find((function (i) {
            return i[/* productId */0] === itemId;
          }), Seed$S2funway.Seed[/* cartItems */0]);
    exit = 1;
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return undefined;
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    return item;
  }
  
}

function handleItem(item) {
  if (item !== undefined) {
    console.log(item[/* title */1] + " found in the cart");
    return /* () */0;
  } else {
    console.log("Item not found");
    return /* () */0;
  }
}

handleItem(getItemById("Book-1"));

handleItem(getItemById("Book-21"));

exports.getItemById = getItemById;
exports.handleItem = handleItem;
/*  Not a pure module */
