// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Seed$S2funway = require("./Seed.bs.js");

var productNames = List.map((function (i) {
        return i[/* title */1];
      }), Seed$S2funway.Seed[/* cartItems */0]);

List.iter((function (pn) {
        console.log(pn);
        return /* () */0;
      }), productNames);

var Seed = Seed$S2funway.Seed;

exports.Seed = Seed;
exports.productNames = productNames;
/* productNames Not a pure module */
