// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var Seed = /* module */[/* cartItems : :: */[
    /* record */[
      /* productId */"Book-1",
      /* title */"Learning Reason ML",
      /* unitPrice */20.00,
      /* currency */"USD",
      /* quantity */5
    ],
    /* :: */[
      /* record */[
        /* productId */"Book-2",
        /* title */"Learning React",
        /* unitPrice */35.00,
        /* currency */"USD",
        /* quantity */4
      ],
      /* :: */[
        /* record */[
          /* productId */"Book-3",
          /* title */"React Quickly",
          /* unitPrice */47.00,
          /* currency */"USD",
          /* quantity */3
        ],
        /* [] */0
      ]
    ]
  ]];

exports.Seed = Seed;
/* No side effect */
